apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: martin-markov-com
  name: martin-markov-com
  namespace: martin-markov
  resourceVersion: "274190"
  uid: 2345c70e-c062-4463-a5cd-9302a70cc5a4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: martin-markov-com
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: martin-markov-com
    spec:
      containers:
      - image: mmark0v/markov-app
        imagePullPolicy: Always
        name: markov-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-29T00:30:13Z"
    lastUpdateTime: "2023-12-29T00:30:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-29T00:29:56Z"
    lastUpdateTime: "2023-12-29T00:30:13Z"
    message: ReplicaSet "martin-markov-com-59b678ff78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---




apiVersion: v1
kind: Service
metadata:
  labels:
    app: martin-markov-com
  name: martin-markov-com
  namespace: martin-markov
  resourceVersion: "274453"
  uid: 835aedb4-04a6-4e40-82de-893be52d0571
spec:
  clusterIP: 
  clusterIPs:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: martin-markov-com
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
