version: '3.7'


services:

  web:
    image: mmark0v/markov-app
    restart: always
    volumes:
      - ./site:/var/www/html
    ports:
      - 8082:80
      - 4432:443
    container_name: martin-markov.com

